version: '3.9'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
